#configuration for gateway

server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # we want to fetch the data from the discovery server
      routes:
        - id: students
          uri: http://localhost:8090
          predicates: #when the path containes the following
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates: #when the path containes the following
            - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
    probability: 1.0