server:
  port: 8888

spring:
  profiles:
    active: native #this means it will automaticly use the native profile
  application:
    name: config-server
  cloud:
    config:
      server:
        native: #means where spring config server will fetch all the conf files
          search-locations: classpath:/configurations
